BACKGROUND_COLOR = (13, 233, 240)

MAX_NUMBER_OF_BOUNCES = 10
TOLERANCE = 1e-10
SAMPLES_PER_PIXEL = 50
FILTER_RADIUS = 1  # 1 means it reaches the centers of adjacent pixels

# settings
BETTER_RANDOM_BOUNCE = True
NUMERICAL_FIX_COLLISION_POINT = True
DEFAULT_COLOR_MIXING_METHOD = "multiply"
USE_ANTIALIASING = True
