BACKGROUND_COLOR = (80, 240, 240)

MAX_NUMBER_OF_BOUNCES = 10

TOLERANCE = 1e-10


# settings
BETTER_RANDOM_BOUNCE = True
NUMERICAL_FIX_COLLISION_POINT = False
DEFAULT_COLOR_MIXING_METHOD = "multiply"
